#In case the values provided to parametrize result in an empty list - for example,
# if they’re dynamically generated by some function -
# the behaviour of pytest is defined by the empty_parameter_set_mark option.

#To get all combinations of multiple parametrized arguments you can stack parametrize decorators:
import pytest


@pytest.mark.parametrize("x", [0, 1])
@pytest.mark.parametrize("y", [2, 3])
def test_foo(x, y):
    print("x" ,x , "y" , y)

    #This will run the test with the arguments set to x=0/y=2, x=1/y=2, x=0/y=3, and x=1/y=3